### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by rachmadaniHaryono** [rachmadaniHaryono/we-get#2]
- [ ] 0.2 version
- [ ] 80% coverage test
- [ ] configurable output
- [ ] database 
- [ ] Fix old credentials (author, email, ...)
- [ ] pypi organization 
- [ ] testing package organization 
- [x] update readme template
- [x] automated code review setup
- [x] better program version (bumpversion)
- [x] contributing guide
- [x] fix flake8
- [x] fix old link
- [x] testing guide
- [ ] config file to change url format

**Comment by Hendrikto** [comment]
I am working on fixing flake8 right now.

**Comment by Hendrikto** [comment]
- [x] Fix old credentials (author, email, ...)

**Comment by rachmadaniHaryono** [comment]
Added

**Comment by mxmilkiib** [comment]
FYI https://aur.archlinux.org/packages/we-get-git/

**Comment by rachmadaniHaryono** [comment]
thank you
